-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.trip
(
    id integer NOT NULL,
    title text NOT NULL,
    description text,
    country_code character varying(3),
    price numeric(12, 2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.booking
(
    id bigserial NOT NULL,
    client_id integer NOT NULL,
    trip_id integer NOT NULL,
    date date NOT NULL,
    status character varying(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment
(
    booking_id integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    method character varying(64) NOT NULL,
    discount numeric(5, 2),
    UNIQUE (booking_id)
);

CREATE TABLE IF NOT EXISTS public.client
(
    id bigserial NOT NULL,
    full_name character varying(128) NOT NULL,
    email character varying(128),
    phone_number character varying(32),
    date_of_birth date,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT client_id FOREIGN KEY (client_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT trip_id FOREIGN KEY (trip_id)
    REFERENCES public.trip (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD FOREIGN KEY (id)
    REFERENCES public.payment (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;